DPDK ring reader
CESNET/ipfixprobe pull request #141
Opened 2023-03-23 13:20 UTC by jaroslavpesek

Added a new input plugin, `dpdk-ring`, which enables ipfixprobe reading from shared memory as a consumer so that ipfixprobe can play the role of DPDK secondary process. See Examples in README.md for checking mandatory parameters.

2023-03-23 15:35 UTC, SiskaPavel commented
Bude to chtit provest rebase

2023-03-24 11:07 UTC, jaroslavpesek commented
rebasnuto

2023-05-16 20:49 UTC, cejkato2 reviewed
There are some coding style issues.

License is not correct.

2023-05-16 20:49 UTC, cejkato2 commented on input/dpdk-ring.cpp
> +DpdkRingCore& DpdkRingCore::getInstance()
```suggestion
DpdkRingCore *DpdkRingCore::m_instance = nullptr;

DpdkRingCore &DpdkRingCore::getInstance()
```

2023-05-16 20:49 UTC, cejkato2 commented on input/dpdk-ring.cpp
> +	struct timeval tv;
```suggestion
    struct timeval tv;
```

2023-05-16 20:49 UTC, cejkato2 commented on input/dpdk-ring.h
> +    static DpdkRingCore& getInstance();
```suggestion
    static DpdkRingCore &getInstance();
```

2023-05-16 20:49 UTC, cejkato2 commented on input/dpdk-ring.h
> +   void configure(const char* params);
```suggestion
   void configure(const char *params);
```

2023-05-16 20:49 UTC, cejkato2 commented on input/dpdk-ring.h
> +    std::vector<char *> convertStringToArgvFormat(const std::string& ealParams);
```suggestion
    std::vector<char *> convertStringToArgvFormat(const std::string &ealParams);
```

2023-05-16 20:49 UTC, cejkato2 commented on input/dpdk-ring.h
> +    void configureEal(const std::string& ealParams);
```suggestion
    void configureEal(const std::string &ealParams);
```

2023-05-16 20:49 UTC, cejkato2 commented on input/dpdk-ring.h
> +    struct timeval getTimestamp(rte_mbuf* mbuf);
```suggestion
    struct timeval getTimestamp(rte_mbuf *mbuf);
```

2023-05-16 20:49 UTC, cejkato2 commented on input/dpdk-ring.h
> +    std::vector<rte_mbuf*> mbufs_;
```suggestion
    std::vector<rte_mbuf *> mbufs_;
```

2023-05-16 20:49 UTC, cejkato2 commented on input/dpdk-ring.h
> +    rte_ring* m_ring;
```suggestion
    DpdkRingCore &m_dpdkRingCore;
    rte_ring *m_ring;
```

2023-05-16 20:49 UTC, cejkato2 commented on input/dpdk-ring.h
> +    Result get(PacketBlock& packets) override;
```suggestion
    Result get(PacketBlock &packets) override;
```

2023-05-16 20:49 UTC, cejkato2 commented on input/dpdk-ring.h
> +    static DpdkRingCore* m_instance;
```suggestion
    static DpdkRingCore *m_instance;
```

2023-05-17 15:26 UTC, cejkato2 requested changes

2023-05-17 15:26 UTC, cejkato2 commented on input/dpdk-ring.cpp
> + *
```suggestion
```

2023-05-17 15:26 UTC, cejkato2 commented on input/dpdk-ring.cpp
> + * Copyright (C) 2021 CESNET
```suggestion
 * Copyright (C) 2023 CESNET
```

2023-05-17 15:26 UTC, cejkato2 commented on input/dpdk-ring.h
> + * Copyright (C) 2021 CESNET
```suggestion
 * Copyright (C) 2023 CESNET
```

2023-05-17 15:26 UTC, cejkato2 commented on input/dpdk-ring.h
> + * if advised of the possibility of such damage.
```suggestion
```

2023-05-19 18:56 UTC, cejkato2 approved these changes

2023-05-19 18:56 UTC, merged