QUIC: Extract more QUIC flow details
CESNET/ipfixprobe pull request #194
Opened 2023-10-26 13:49 UTC by jmuecke

We extend ipfixprobe's quic module by extracting the following additional QUIC meta information:

|    Output field     |  Type  |                               Description                               |
|:-------------------:|:------:|:-----------------------------------------------------------------------:|
| QUIC_CLIENT_VERSION | uint32 |     QUIC version from the Initial packet with the TLS Client Hello      |
|  QUIC_TOKEN_LENGTH  | uint64 |               Token length from Initial and Retry packets               |
|     QUIC_OCCID      | string |   Source Connection ID from Initial packet with the TLS Client Hello    |
|     QUIC_OSCID      | string | Destination Connection ID from Initial packet with the TLS Client Hello |
|      QUIC_SCID      | string |    Source Connection ID from long header packets other than before.     |
|   QUIC_RETRY_SCID   | string |                 Source Connection ID from Retry packet                  |
|  QUIC_MULTIPLEXED   | uint8  |          > 0 if multiplexed (at least two QUIC_OSCIDs or SNIs)          |
|    QUIC_ZERO_RTT    | uint8  |                   Number of 0-RTT packets in flow.                   |

**Additional improvements:**

- Previously ipfixprobe detected QUIC flows as UDP flows on port 443 that include a QUIC Initial packet. **The new detection is requires the transport protocol UDP, a minimum length for long header packets, a known QUIC version and a QUIC long header packet.**
- Previously ipfixprobe only considered the first QUIC packet in the UDP payload. **We now parse all coalesced packets with a long header.**
- We extract both versions in [compatible version negotiation](https://datatracker.ietf.org/doc/html/rfc9368).
- The retry token length is extracted from Retry packets.
- We detect if the same 5/4-tuple is used by multiple different QUIC connections. 

**Limitations:**

- We are unable to detect client migration and subsequently added paths (Multipath QUIC).
- We do not parse any short header packets.

2023-10-31 13:02 UTC, hynekkar requested changes
Hi Jonas, Thank you very much for your effort! I have small comments on your contribution. Besides, I would like to ask you about code formatting according to the .clang-format file in the repository root. Any modern IDE should understand this code formatting.

2023-10-31 13:02 UTC, hynekkar commented on README.md
> +|     QUIC_OCCID      | string |   Source Connection ID from Initial packet with the TLS Client Hello    |
Can you please put **bytes** instead of string in the types of *CID fields? You have the correct type in the code, but a wrong one in README.

2023-10-31 13:02 UTC, hynekkar commented on include/ipfixprobe/ipfix-elements.hpp
> +#define QUIC_ZERO_RTT(F)              F(8057,    900,   1,   nullptr)
```suggestion
#define QUIC_ZERO_RTT(F)              F(8057,    889,   1,   nullptr)
```
The IPFIX ID 8057:900 is already used (line 119 in this file). Please use the ID 8057:889 to keep the continuous range assigned for QUIC fields.

2023-10-31 13:02 UTC, hynekkar commented on process/quic.cpp
> +            memcpy(quic_data->scid, ext->dir_dcid, quic_data->scid_length);
The correct value of scid_length has to be checked always before use!
If the SCID  len is wrongly filled by the quick client or other parsing problems occur, ipfixprobe experiences segfault.

During the live testing, there was quic_data->occid_length==192... so please check...

2023-10-31 18:08 UTC, jmuecke commented on README.md
> +|     QUIC_OCCID      | string |   Source Connection ID from Initial packet with the TLS Client Hello    |
yes, done!

2023-10-31 18:08 UTC, jmuecke commented on include/ipfixprobe/ipfix-elements.hpp
> +#define QUIC_ZERO_RTT(F)              F(8057,    900,   1,   nullptr)
Also resolved.

2024-04-03 11:15 UTC, SiskaPavel commented
Modify this if statement:

```
process/quic.cpp: In member function ‘void ipxp::QUICPlugin::set_client_hello_fields(ipxp::QUICParser*, ipxp::Flow&, ipxp::RecordExtQUIC*, const ipxp::Packet&, bool)’:
process/quic.cpp:265:33: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
  265 |             || (!new_quic_flow) && (quic_data->retry_scid_length == dcid_len))
      |                ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     ```

2024-04-16 20:09 UTC, jmuecke commented
I applied the commit and modifeied that codition to get rid of the compiler warning. 

I also changed part or the retry code, to only act upon the first retry packet.

2024-04-22 13:19 UTC, merged