NetBIOS
CESNET/ipfixprobe pull request #7
Opened 2020-10-15 10:05 UTC by xsedla1o

Plugin allowing to capture NetBIOS names with suffixes from NBNS.

2020-10-15 11:52 UTC, havraji6 commented on netbiosplugin.cpp
> +const char *ipfix__template[] = {
this should be `ipfix_netbios_template`

2020-10-15 12:13 UTC, havraji6 requested changes

2020-10-15 12:13 UTC, havraji6 commented on Makefile.am
missing netbios pcap sample in `EXTRA_DIST`

2020-10-15 12:13 UTC, havraji6 commented on netbiosplugin.cpp
> +        string NB_NAME,
excessive number of spaces

2020-10-16 13:47 UTC, havraji6 approved these changes

2020-10-22 07:11 UTC, xsedla1o commented
Summary of changes since last approval:
- The branch was rebased on top of master and the merge conflicts with newly added `idpcontent` plugin were resolved.
- The field type of NB_SUFFIX was changed from `bytes` to `uint8`. This was done because the suffix is always one byte long, and therefore the plugin would never utilize the variable-length `bytes` type fully.
- A dist build error that was caused by adding a non-existent target to `Makefile.am` during resolving merge conflicts was fixed.

2020-10-22 11:11 UTC, havraji6 approved these changes

2020-11-07 09:38 UTC, cejkato2 approved these changes

2020-11-07 09:39 UTC, merged